echo output

diff --git a/0x0D-web_stack_debugging_0/0-give_me_a_page b/0x0D-web_stack_debugging_0/0-give_me_a_page
--- a/0x0D-web_stack_debugging_0/0-give_me_a_page
+++ b/0x0D-web_stack_debugging_0/0-give_me_a_page
@@ -1,3 +1,8 @@
 #!/usr/bin/env bash
 # Run apache in the docker container
 service apache2 start
+
+if ! service apache2 staus | grep -q "apache2 is running"; then
+	echo "Error: Apache is not running."
+	exit 1
+fi
